# Generated by Django 2.2.4 on 2022-12-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yasmeenFirst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
